config/routes.rb
Rails.application.routes.draw do

  get 'contacts' => 'contacts#new'
  post 'contacts' =>'contacts#create'
  get 'contacts/complete' => 'contacts#complete'
  devise_for :users, controllers:{
  	sessions: 		'users/sessions',
  	passwords: 		'users/passwords',
  	registarations: 'users/registarations'
  }

  root 'abouts#index'
  resources :users, only: [:show, :edit, :update ]
  get 'users/:id/mypost' => 'users#mypost', as: 'mypost_user'
  resources :travel_posts do
    resources :comments, only: [:create]
  end
  resources :likes, only: [:create, :destroy]
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/travel_post.rb
class TravelPost < ApplicationRecord
	belongs_to :user
	belongs_to :tag

	validates :user_id, presence: true
	validates :title, presence: true
	validates :body, presence: true
	attachment :image

end

app/controllers/travel_posts_controller.rb
class TravelPostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_travel_post, only: [:show, :edit, :update, :destroy]

	# GET /travel_posts
	# GET /travel_posts.json
	def index
		if params[:tag_id]
			@tag = Tag.find(params[:tag_id])
			@travel_posts = @tag.travel_posts.page(params[:page]).per(8)
			@post = TravelPost.new
		else
			@travel_posts = TravelPost.page(params[:page]).per(8)
			@post = TravelPost.new
		end
	end
	# GET /travel_posts/1
	# GET /travel_posts/1.json
	def show
		@post = TravelPost.find(params[:id])
		@user = @travel_post.user
		# 投稿に紐づけたタグの取得
		@travel_post = TravelPost.find(params[:id])
	end

	# GET /travel_posts/new
	def new
		@travel_post = TravelPost.new
	end

	# GET /travel_posts/1/edit
	def edit
		@user = @travel_post.user
		@tag = Tag.find(params[:id])
	end
	def user
		return User.find_by(id:self.user_id)
	end

	# POST /travel_posts
	# POST /travel_posts.json
	def create
		@post = TravelPost.new(travel_post_params)
		@post.user_id = current_user.id
		respond_to do |format|
    		if @post.save(travel_post_params)
        		format.html { redirect_to travel_posts_path(@post.id), notice: 'Travel post was successfully created.' }
        		format.json { render :show, status: :created, location: @post }
    		else
    			@travel_post = TravelPost.new
        		format.html { render :new }
        		format.json { render json: @travel_post.errors, status: :unprocessable_entity }
    		end
    	end
  	end

	# PATCH/PUT /travel_posts/1
	# PATCH/PUT /travel_posts/1.json
	def update
    	respond_to do |format|
    		@travel_post = TravelPost.find(params[:id])
    		if @travel_post.update(travel_post_params)
        		format.html { redirect_to @travel_post, notice: 'Travel post was successfully updated.' }
        		format.json { render :show, status: :ok, location: @travel_post }
      		else
        		format.html { render :edit }
        		format.json { render json: @travel_post.errors, status: :unprocessable_entity }
    		end
    	end
	end

	# DELETE /travel_posts/1
	# DELETE /travel_posts/1.json
	def destroy
		travel_post = TravelPost.find(params[:id])
	    if travel_post.destroy
    		redirect_to travel_posts_path
    	else
    		render :edit
    	end
	end
	def search
		@tag_list = Tag.all  #全てのタグを表示するために、タグを全取得
		@tag = Tag.find(params[:tag_id])  #タグを取得
		@posts = @tag.posts.all           #タグに紐付けられた投稿を全て表示
	end

	def save_tags
    current_tags = self.tagss.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      travel_post_tag = Tag.find_or_create_by(name:new_name)
      self.tags << travel_post_tag
    end
  end





	private
    # Use callbacks to share common setup or constraints between actions.
    	def set_travel_post
    		@travel_post = TravelPost.find(params[:id])
    	end

    # Only allow a list of trusted parameters through.
    	def travel_post_params
    		params.require(:travel_post).permit(:user_id, :image, :title, :body, :price, :img, :tag_id, :content )
    	end
end

app/helpers/travel_posts_helper.rb
module TravelPostsHelper
end

app/views/travel_posts/_form.html.erb
<!-- 新規投稿画面 、　編集画面-->
<div class="wrapper">
  <div class="form">
    <h2>投稿画面</h2>
    <%= form_with(model: travel_post, local: true) do |f| %>
      <% if travel_post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(travel_post.errors.count, "error") %> prohibited this travel_post from being saved:</h2>
          <ul>
          <% travel_post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-item">
        <p><%= f.label :title, "旅行場所名　（必須）" %></p>
        <%= f.text_field :title %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="form-item">
        <p><%= f.label :image, "旅行画像" %></p>
        <%= f.attachment_field :image, size:'100x100' %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="form-item">
        <p><%= f.label :price, "旅行金額" %></p>
        <%= f.number_field :price %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="form-item">
        <p><%= f.label :body, "旅行内容" %></p>
        <%= f.text_area :body, size:"50x20" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div class="form-item">
        <!-- タグのチェックボックス -->
        <%= f.label :tag, "タグを選択してください" %>
          <ul id="article-tags">
            <%= f.collection_select :tag_id, Tag.all, :id, :name, prompt:"選択してください" %>
          </ul>
          <div class="actions">
            <%= f.submit "投稿",class: 'btn btn-primary'  %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/travel_posts/edit.html.erb
<%= render 'form', travel_post: @travel_post %>

<%= link_to 'Show', @travel_post %> |
<%= link_to 'Back', travel_posts_path %>

app/views/travel_posts/index.html.erb
<!-- 投稿一覧画面 -->
<%=form_tag travel_posts_path, method: :get, class: 'boards_searchForm' do %>
	<%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),{ prompt: 'タグで絞り込み検索',onchange: 'submit(this.form);'}%>
	<% end %>
<h2>投稿一覧(全<%= @travel_posts.count %>件)</h2>
<div class="d-flex">
	
		<% @travel_posts.each do |travel_post| %>
		<div class="flex-item">
				<%= link_to travel_post_path(travel_post.id),style: "color: black;", data: {"turbolinks" => false} do %>
					<%= attachment_image_tag travel_post, :image,format: 'jpeg', fallback: "no_image.jpg" %><br>
					
					<%= travel_post.created_at.strftime('%Y/%m/%d') %>
					<%= travel_post.title %>
			<!-- タグ　表示 -->
						<%= travel_post.tag.name %>
					<%= travel_post.user.name %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>
<div style="text-align: center;"><%= paginate @travel_posts %></div>

app/views/travel_posts/new.html.erb
<%= render 'form', travel_post: @travel_post %>

<%= link_to '戻る', travel_posts_path %>

app/views/travel_posts/show.html.erb
<h3>投稿詳細</h3>
<div class="mypage">
	<table>
		<tr>
			<td>投稿名</td>
			<td><%= @post.title %></td>
		</tr>
		<tr>
			<td>投稿画像</td>
			<td><%= attachment_image_tag @post, :image, format: 'jpeg' %></td><br>
		</tr>
		<tr>
			<td>投稿内容</td>
			<td><%= markdown(@post.body).html_safe %></td>
		</tr>
		<tr>
			<td>タグ</td>
			<td>
				<%= @post.tag.name %>
			</td>
		</tr>
		<tr>
			<td>ユーザ名</td>
			<td><%= @post.user.name %></td>
		</tr>

	</table>
	<% if @user == current_user %>
		<%= link_to "編集する", edit_travel_post_path, class: "btn btn-primary" %>
		<%= link_to "削除する", travel_post_path(@post),class: "btn btn-danger", method: :DELETE, data:{confirm:"本当に消しますか？"} %>
	<% end %>

	<%= link_to "投稿一覧へ戻る", travel_posts_path, class: "btn btn-primary" %>
</div>