config/routes.rb
Rails.application.routes.draw do

  get 'contacts' => 'contacts#new'
  post 'contacts' =>'contacts#create'
  get 'contacts/complete' => 'contacts#complete'
  devise_for :users, controllers:{
  	sessions: 		'users/sessions',
  	passwords: 		'users/passwords',
  	registarations: 'users/registarations'
  }

  root 'abouts#index'
  resources :users, only: [:show, :edit, :update ]
  get 'users/:id/mypost' => 'users#mypost', as: 'mypost_user'
  resources :travel_posts do
    resources :comments, only: [:create]
  end
  resources :likes, only: [:create, :destroy]
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :travel_posts, dependent: :destroy

   def already_liked?(travel_post)
    self.likes.exists?(travel_post_id: travel_post.id)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		 @user = User.find(params[:id])
		 @users = User.all
	end
	def edit
		@user = current_user
	end

	def mypost
		@travel_posts = current_user.travel_posts.all
		@serch = TravelPost.ransack(params[:q])
		@posts = @serch.result.page(params[:page]).per(8)
	end

	def update
		@user = current_user
		if @user.update(user_params)
			flash[:success] = "登録情報を変更しました。"
			redirect_to user_path(current_user)
		else
			render edit_user_path(current_user)
		end
	end
	def likes
		@user = User.find_by(id: params[:id])
		@likes = Like.where(user_id: @user.id)
		@post = TravelPost.find_by(id: @likes.travel_post_id)
	end
	private
	def user_params
		params.require(:user).permit(:name,:email)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- マイページ編集画面 -->
<div class="mypage">
  <%= form_with model: @user do |f| %>
		<h3><strong>登録情報編集</strong></h3>
    <hr>
    	<%= f.label :"ユーザ名" %>
      <%= f.text_field :name %><br>
      <%= f.label :"メールアドレス" %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email"   %>
    <div class="actions col-xs-10 col-xs-offset-2">
      <p><%= f.submit "変更する", class: "btn btn-primary" %></p>
   	</div>
  <% end %>
</div>

app/views/users/mypost.html.erb
<%=form_tag travel_posts_path, method: :get, class: 'boards_searchForm' do %>
	<%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
	{ prompt: 'タグで絞り込み検索',onchange: 'submit(this.form);'}%>
	<% end %>
<h2>投稿一覧(全<%= @travel_posts.count %>件)</h2>
<div class="d-flex">
	
		<% @travel_posts.last(9).each do |travel_post| %>
		<div class="flex-item">
				<%= link_to travel_post_path(travel_post.id),style: "color: black;", data: {"turbolinks" => false} do %>
					<%= image_tag travel_post.img.url, fallback: "no_image.jpg" %><br>
					
					<%= travel_post.created_at.strftime('%Y/%m/%d') %>
					<%= travel_post.title %>
			<!-- タグ　表示 -->
						<%= travel_post.tag.name %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>
<div style="text-align: center;"><%= paginate @posts %></div>

app/views/users/show.html.erb
<!--マイページ画面 -->
<div class="mypage">
    <h3><strong>マイページ</strong></h3><hr>
    <table class="table table-bordered table-condensed">
        <strong class="information-link">登録情報 </strong>
        <%= link_to " 編集する ", edit_user_path, class: "glyphicon glyphicon-pencil btn btn-success" %>&nbsp;
        <strong class="shipping-link">新規投稿　</strong>
        <%= link_to " 投稿する ", new_travel_post_path, class: "glyphicon glyphicon-folder-open btn btn-info" %>
        <tr>
            <td>ユーザ名</td>
            <td><%= @user.name %></td>
        </tr>
        <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
        </tr>
    </table>
        <p>
            <strong>投稿履歴</strong>
            <%= link_to " 一覧を見る", mypost_user_path , class: "glyphicon glyphicon-folder-open btn btn-info" %>
        </p>
</div>