config/routes.rb
Rails.application.routes.draw do

  get 'contacts' => 'contacts#new'
  post 'contacts' =>'contacts#create'
  get 'contacts/complete' => 'contacts#complete'
  devise_for :users, controllers:{
  	sessions: 		'users/sessions',
  	passwords: 		'users/passwords',
  	registarations: 'users/registarations'
  }

  root 'abouts#index'
  resources :users, only: [:show, :edit, :update ]
  get 'users/:id/mypost' => 'users#mypost', as: 'mypost_user'
  resources :travel_posts do
    resources :comments, only: [:create]
  end
  resources :likes, only: [:create, :destroy]
  resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
		<div class="small text-center" style="margin: 50px 0;">
			Copyright © 2020 travel-Book</div>
		</div>
</footer>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<!-- ログイン中の場合 -->
     <header>
          <div class="header-content">
               <ul class="nav-header">
                    <div class="mr-auto"><%= link_to image_tag("logo.png"), root_path, class: "logo" %></div>
                         <li><%= link_to "マイページ", user_path(current_user), class: "nav-button" %></li>
                         <li><%= link_to "投稿一覧", travel_posts_path, class: "nav-button" %></li>
                         <li><%= link_to "お問い合わせ", contacts_path, class: "nav-button"%></li>
                         <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-button" %></li>
               </ul>
          </div>
     </header>
<% else %>
<!-- 未ログインの場合 -->
     <header>
          <div class="header-content">
               <ul class="nav-header">
                    <div class="mr-auto"><%= link_to image_tag("logo.png"), root_path, class: "logo" %></div>
                         <li><%= link_to "新規登録", new_user_registration_path, class: "nav-button" %></li>
                         <li><%= link_to "お問い合わせ", contacts_path,class: "nav-button" %></li>
                         <li><%= link_to "ログイン", new_user_session_path, class: "nav-button" %></li>
                    </ul>
     	    </ul>
          </div>
     </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://kit.fontawesome.com/e9f5ec0232.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="body">
    <!-- ヘッダー -->
      <div id="header">
          <%= render "layouts/header" %>
      </div>
      <div class="flex">
        <%= yield %>
      </div>
    <!-- フッター -->
        <%= render "layouts/footer" %>
      <% else %>
    </div>

  </body>
</html>